name: Build APK
on: push
jobs:
  Build-APK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build APK with Gradle
        env:
          CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
          CLIENT_REDIRECT_URL: ${{ secrets.ANILIST_REDIRECT_URL }}
        run: ./gradlew assembleRelease -PCLIENT_ID=$CLIENT_ID -PCLIENT_SECRET=$CLIENT_SECRET -PCLIENT_REDIRECT_URL=$CLIENT_REDIRECT_URL

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/release/app-release.apk
