name: Build APK
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        options:
          - Major
          - Minor
          - Patch
jobs:
  BuildAPK:
    name: Build APK version ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Update version tag
        run: |
          case $inputs.version in
              Major)  curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_MAJOR
                          -d '{"name": "VERSION_MAJOR", "value": $((${{ vars.VERSION_MAJOR }}+1))}'
                      curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_MINOR
                          -d '{"name": "VERSION_MINOR", "value": 0}'
                      curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_PATCH
                          -d '{"name": "VERSION_PATCH", "value": 0}'
                      ;;
              Minor)  curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_MINOR
                          -d '{"name": "VERSION_MINOR", "value": $((${{ vars.VERSION_MINOR }}+1))}'
                      curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_PATCH
                          -d '{"name": "VERSION_PATCH", "value": 0))}'
                      ;;
              Patch)  curl -L -X PATCH -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          https://api.github.com/repos/dannful/Tenkai/actions/variables/VERSION_PATCH
                          -d '{"name": "VERSION_PATCH", "value": "$((${{ vars.VERSION_PATCH }}+1))"}'
                      ;;
          esac

#      - name: Build APK with Gradle
#        env:
#          CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
#          CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
#          CLIENT_REDIRECT_URL: ${{ secrets.ANILIST_REDIRECT_URL }}
#        run: ./gradlew assembleRelease -PVERSION_CODE=${{ github.run_number }} -PVERSION_NAME="${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}" -PCLIENT_ID=$CLIENT_ID -PCLIENT_SECRET=$CLIENT_SECRET -PCLIENT_REDIRECT_URL=$CLIENT_REDIRECT_URL
#
#      - name: Create release
#        uses: softprops/action-gh-release@v2
#        id: create_release
#        with:
#          files: |
#            app/build/outputs/apk/release/app-release.apk
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag_name: ${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}
#          name: Release ${{ inputs.version }}

